# based on https://github.com/johnfactotum/foliate/blob/gtk4/.github/workflows/deb.yml

name: Build and Upload Debian Package

# Controls when the action will run. 
on:
  # Triggers the workflow on release publication
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - run: sudo apt-get update
      - run: sudo apt-get install build-essential debhelper meson python3-setuptools dh-make
      - run: DPKG_DEB_COMPRESSOR_TYPE=xz dpkg-buildpackage -us -uc -nc
      - run: mv ../*.deb .

      # Upload the .deb package to the GitHub release
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.deb"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
