name: Sync to gh-pages

on:
  push:
    branches:
      - master
    paths:
      - 'typhoon/script.js'
      - 'typhoon/style.css'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master
          path: master

      - name: Copy updated files
        run: |
          cp master/typhoon/script.js gh-pages/webapp/script.js
          cp master/typhoon/style.css gh-pages/webapp/style.css

      - name: Commit and push changes
        run: |
          cd gh-pages
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add webapp/script.js webapp/style.css
          git commit -m "Update script.js and style.css from master" || echo "No changes to commit"
          git push origin gh-pages